development:
  sessions:
    default:
      database: WDES_development
      hosts:
        - 'localhost:27017'
test:
  sessions:
    default:
      database: WDES_test
      hosts:
        - 'localhost:27017'
production:
  sessions:
    default:
      database: WDES_production
      hosts:
        - 'localhost:27017'
